### ISSUE TITLE
AddMsgList[0].RecommendInfo.AttrStatus要为long

### ISSUE THREAD

**Issue by twbbb** [xuxiaoxiao-xxx/ChatApi-WeChat#10]
有个报错：AddMsgList[0].RecommendInfo.AttrStatus要为long
四月 10, 2019 11:28:45 下午 me.xuxiaoxiao.chatapi.wechat.WeChatClient$WeChatThread listen
较详细: 监听2: wxAPI.syncCheckKey:1_669177820|2_669184059|3_669183729|11_669184040|201_1554909927|203_1554909777|1000_1554884963|1001_1554885202,wxAPI.synckey:1_669177820|2_669184059|3_669183729|11_669184040|201_1554909927|203_1554909777|1000_1554884963|1001_1554885202
com.google.gson.JsonSyntaxException: java.lang.NumberFormatException: Expected an int but was 2147487933 at line 37 column 25 path $.AddMsgList[0].RecommendInfo.AttrStatus
        at com.google.gson.internal.bind.TypeAdapters$7.read(TypeAdapters.java:228)
        at com.google.gson.internal.bind.TypeAdapters$7.read(TypeAdapters.java:218)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:131)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:222)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:131)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:222)
        at com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:41)
        at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:82)
        at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:61)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:131)
        at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:222)
        at com.google.gson.Gson.fromJson(Gson.java:927)
        at com.google.gson.Gson.fromJson(Gson.java:892)
        at com.google.gson.Gson.fromJson(Gson.java:841)
        at com.google.gson.Gson.fromJson(Gson.java:813)
        at me.xuxiaoxiao.chatapi.wechat.WeChatApi.webwxsync(WeChatApi.java:209)
        at me.xuxiaoxiao.chatapi.wechat.WeChatClient$WeChatThread.listen(WeChatClient.java:706)
        at me.xuxiaoxiao.chatapi.wechat.WeChatClient$WeChatThread.run(WeChatClient.java:573)
Caused by: java.lang.NumberFormatException: Expected an int but was 2147487933 at line 37 column 25 path $.AddMsgList[0].RecommendInfo.AttrStatus
        at com.google.gson.stream.JsonReader.nextInt(JsonReader.java:1172)
        at com.google.gson.internal.bind.TypeAdapters$7.read(TypeAdapters.java:226)
        ... 17 more
四月 10, 2019 11:28:45 下午 me.xuxiaoxiao.chatapi.wechat.WeChatClient$WeChatThread listen

**Comment by xuxiaoxiao-xxx** [comment]
收到，非常感谢
