### ISSUE TITLE
 最近两天connect timed out

### ISSUE THREAD

**Issue by twbbb** [xuxiaoxiao-xxx/ChatApi-WeChat#21]
java.net.SocketTimeoutException: connect timed out
        at java.net.PlainSocketImpl.socketConnect(Native Method)
        at java.net.AbstractPlainSocketImpl.doConnect(AbstractPlainSocketImpl.java:350)
        at java.net.AbstractPlainSocketImpl.connectToAddress(AbstractPlainSocketImpl.java:206)
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:188)
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
        at java.net.Socket.connect(Socket.java:589)
        at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:668)
        at sun.net.NetworkClient.doConnect(NetworkClient.java:175)
        at sun.net.www.http.HttpClient.openServer(HttpClient.java:432)
        at sun.net.www.http.HttpClient.openServer(HttpClient.java:527)
        at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:264)
        at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:367)
        at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:191)
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1138)
        at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1032)
        at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177)
        at sun.net.www.protocol.http.HttpURLConnection.getOutputStream0(HttpURLConnection.java:1316)
        at sun.net.www.protocol.http.HttpURLConnection.getOutputStream(HttpURLConnection.java:1291)
        at sun.net.www.protocol.https.HttpsURLConnectionImpl.getOutputStream(HttpsURLConnectionImpl.java:250)
        at me.xuxiaoxiao.xtools.common.http.XHttpTools.http(XHttpTools.java:53)
        at me.xuxiaoxiao.xtools.common.XTools.http(XTools.java:99)
        at me.xuxiaoxiao.chatapi.wechat.WeChatApi.webwxsync(WeChatApi.java:209)
        at me.xuxiaoxiao.chatapi.wechat.WeChatClient$WeChatThread.listen(WeChatClient.java:706)
        at me.xuxiaoxiao.chatapi.wechat.WeChatClient$WeChatThread.run(WeChatClient.java:573)
java.lang.NullPointerException
        at java.io.Reader.<init>(Reader.java:78)
        at java.io.InputStreamReader.<init>(InputStreamReader.java:97)
        at me.xuxiaoxiao.xtools.common.XTools.streamToStr(XTools.java:275)
        at me.xuxiaoxiao.xtools.common.http.XResponse.string(XResponse.java:46)
        at me.xuxiaoxiao.xtools.common.http.XResponse.string(XResponse.java:36)
        at me.xuxiaoxiao.chatapi.wechat.WeChatApi.webwxsync(WeChatApi.java:209)
        at me.xuxiaoxiao.chatapi.wechat.WeChatClient$WeChatThread.listen(WeChatClient.java:706)
        at me.xuxiaoxiao.chatapi.wechat.WeChatClient$WeChatThread.run(WeChatClient.java:573)
java.lang.NullPointerException
七月 02, 2019 7:38:20 下午 me.xuxiaoxiao.chatapi.wechat.WeChatClient$WeChatThread listen
警告: 监听消息异常：
[]

**Comment by xuxiaoxiao-xxx** [comment]
我也不是很清楚原因，偶现的话考虑网络问题吧

**Comment by twbbb** [comment]
恩，不过我觉得偶尔超时不能导致机器人挂掉，我在外层加了一个try catch，不过还没部署。
