### ISSUE TITLE
登录出现错误：登陆异常

### ISSUE THREAD

**Issue by Itsusinn** [xuxiaoxiao-xxx/ChatApi-WeChat#25]
这是我在new了一个对象然后startup()后的情况

`请输入指令
2020-02-17 20:24:13.418 | D | Thread-0 | chatapi-wechat | 正在登录
2020-02-17 20:24:14.122 | D | Thread-0 | chatapi-wechat | 等待扫描二维码：https://login.weixin.qq.com/qrcode/4bAFe8Iz6w==
onQRCode：https://login.weixin.qq.com/qrcode/4bAFe8Iz6w==
2020-02-17 20:24:34.989 | D | Thread-0 | chatapi-wechat | 已扫描二维码
2020-02-17 20:24:36.961 | D | Thread-0 | chatapi-wechat | 已授权登录
java.lang.StringIndexOutOfBoundsException: String index out of range: -7
        at java.lang.String.substring(String.java:1967)
        at me.xuxiaoxiao.chatapi.wechat.WeChatApi.webwxnewloginpage(WeChatApi.java:108)
        at me.xuxiaoxiao.chatapi.wechat.WeChatClient$WeChatThread.login(WeChatClient.java:729)
        at me.xuxiaoxiao.chatapi.wechat.WeChatClient$WeChatThread.run(WeChatClient.java:679)
2020-02-17 20:24:37.330 | W | Thread-0 | chatapi-wechat | 登录异常
String index out of range: -7
java.lang.String.substring(String.java:1967)
me.xuxiaoxiao.chatapi.wechat.WeChatApi.webwxnewloginpage(WeChatApi.java:108)
me.xuxiaoxiao.chatapi.wechat.WeChatClient$WeChatThread.login(WeChatClient.java:729)
me.xuxiaoxiao.chatapi.wechat.WeChatClient$WeChatThread.run(WeChatClient.java:679)
2020-02-17 20:24:37.331 | E | Thread-0 | chatapi-wechat | 登录出现错误：登陆异常`

**Comment by Itsusinn** [comment]
额,,,,我去试了一下官方的网页微信
是因为我账号安全问题导致不能登陆

> 为了你的帐号安全，此微信号不能登录网页微信。你可以使用Windows微信或Mac微信在电脑端登录。

**Comment by xuxiaoxiao-xxx** [comment]
收到
